spring:
  application:
    name: api-gateway
    
server:
  port: ${PORT:${SERVER_PORT:0}}
  
ribbon:
   eureka:
      enabled: true
      
eureka:
  instance:
      hostname: localhost
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
