spring:
  application:
    name: transaction-service

kafka:
  bootstrap-servers: localhost:9092 #10.0.1.6:9092,10.0.1.253:9092,10.0.1.174:9092

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
