spring:
  application:
    name: uaa-service

server:
  port: 8769
  context-path: /uaa
  use-forward-headers: false

eureka:
  instance:
      hostname: 10.0.1.164
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

security:
  basic:
    enabled: false
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

logging:
  level.org.springframework.security: DEBUG
