spring:
  application:
    name: otp-stream

kafka:
  bootstrap-servers: 10.0.1.253:9092,10.0.1.174:9092,10.0.1.6:9092 #10.0.1.108:9092
  inputTopic: validate-otp
  outputSuccessTopic: otp-success
  outputFailureTopic: otp-failure

eureka:
  instance:
      hostname: 10.0.1.104
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true
redis:
  server: 10.0.1.110
  port: 6379
logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
