spring:
  application:
    name: otp-consumer
kafka:
  bootstrap-servers: 10.0.1.108:9092
eureka:
  client:
    service-url:
      default-zone: http://10.0.1.104:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
