spring:
  application:
    name: otp-stream

kafka:
  inputTopic: validate-otp
  outputSuccessTopic: otp-success
  outputFailureTopic: otp-failure

eureka:
  instance:
      hostname: localhost
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
