spring:
  application:
    name: otp-stream

kafka:
  inputTopic: validate-otp
  outputSuccessTopic: otp-success
  outputFailureTopic: otp-failure

eureka:
  instance:
      hostname: 10.0.1.104
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
redis:
  server: 10.0.1.110
logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
