spring:
  application:
    name: otp-consumer
kafka:
  bootstrap-servers: localhost:9092
server:
  port: 9988
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    com.sapient: DEBUG
  file: log/my.log