spring:
  application:
    name: otp-stream

server:
  port: 8998

kafka:
  inputTopic: validate-otp
  outputSuccessTopic: otp-success
  outputFailureTopic: otp-failure

logging:
  level:
    com.sapient: DEBUG
  file: log/my.log