spring:
  application:
    name: otp-success-topic-consumer

 

kafka:
  bootstrap-servers: localhost:9092

 

server:
  port: 9999
logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true