server:
  port: 8998
spring:
  application:
    name: otp-stream
kafka:
  inputTopic: validate-otp
  outputSuccessTopic: otp-success
  outputFailureTopic: otp-failure
logging:
  level:
    com.sapient: DEBUG
  file: log/my.log