spring:
  application:
    name: service-registry

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    port: ${server.port}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

logging:
  level:
    com.sapient: DEBUG
  file: log/my.log

