spring:
  application:
    name: transaction-limit-stream

kafka:
  bootstrap-servers: 10.0.1.253:9092,10.0.1.174:9092,10.0.1.6:9092
  inputTopic: otp-success
  outputSuccessTopic: transaction-limit-success
  outputFailureTopic: transaction-limit-failure

logging:
  level:
    com.sapient: DEBUG
  file: log/my.log

mongo:
  server: 10.0.1.110
