spring:
  application:
    name: transaction-limit-success-consumer

server:
  port: 9999

kafka:
  bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.sapient: DEBUG
  file: log/my.log