spring:
  application:
    name: transaction-limit-stream

server:
  port: 8999

kafka:
  inputTopic: otp-success
  outputSuccessTopic: transaction-limit-success
  outputFailureTopic: transaction-limit-failure

logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
