spring:
  application:
    name: transaction-result-producer
    
kafka:
  bootstrap-servers: localhost:9092
  topic: otp-input20

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level.com.sapient: DEBUG
  file: log/my.log
