spring:
  application:
    name: transaction-log-consumer
  data:
    mongodb:
      host: 10.0.1.110
      port: 27017
      authentication-database: admin
      database: transaction_log
      
kafka:
  bootstrap-servers: 10.0.1.6:9092,10.0.1.253:9092,10.0.1.174:9092

eureka:
  instance:
      hostname: 10.0.1.104
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
