spring:
  application:
    name: transaction-service

kafka:
  bootstrap-servers: 10.0.1.6:9092,10.0.1.253:9092,10.0.1.174:9092 #10.0.1.108:9092 #change

eureka:
  instance:
      hostname: 10.0.1.104
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    registerWithEureka: true
    fetchRegistry: true
logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
