spring:
  application:
    name: transaction-status-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: transaction_log


ribbon:
  eureka:
    enabled: true
      
feign:
  hystrix:
    enabled: true
    
hystrix:
  shareSecurityContext: true

security:
  basic:
    enabled: false
  oauth2:
    client:
    resource:
      id: openid
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      user-info-uri: http://localhost:8769/uaa/user/me
      token-info-uri: http://localhost:8769/uaa/oauth/check_token
      
eureka:
  instance:
    hostname: 10.0.1.104
    port: 8761
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

logging:
  level:
    com:
      sapient: DEBUG
  file:log/my.log
