spring:
  application:
    name: userprofile-consumer
    
kafka:
  bootstrap-servers: 10.0.1.108:9092

eureka:
  instance:
      hostname: 10.0.1.104
      port: 8761
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
      
logging:
  level:
    com.sapient: DEBUG
  file: log/my.log
